apiVersion: apps/v1

kind: Deployment

metadata:

  name: wordpress-ihm

  labels:

    app: wp-ihm

spec:

  replicas: 1

  selector:

    matchLabels:

      app: wp-ihm

  template:

    metadata:

      labels:

        app: wp-ihm
        
    spec:

      containers:

      - name: wordpress-ihm

        image: wordpress

        ports:

        - containerPort: 80

        env:
          - name: WORDPRESS_DB_HOST
            
            value: services-db
          
          - name: WORDPRESS_DB_USER
          
            value: alice

          - name: WORDPRESS_DB_PASSWORD

            value: password

          - name: WORDPRESS_DB_NAME

            value: wordpress_db



