apiVersion: v1

kind: Service

metadata:

  labels:

    wp-app: services-db

  name: services-db

spec:

  selector:

    app: wp-bdd

  type: ClusterIP

  ports:
    
    - protocol: TCP

      port: 3306

      targetPort: 3306
