apiVersion: v1

kind: Service

metadata:

  labels:

    wp-app: services-ihm

  name: services-ihm

spec:

  selector:

    app: wp-ihm
   
  type: ClusterIP

  ports:
    
    - protocol: TCP

      port: 3306

      targetPort: 3306
